from typing import Protocol

from gomazon_webasyst.contracts.dispatch import HandlerKey, ModuleHandlerKey


class DispatchRegistry(Protocol):
    def controller_id(self, key: HandlerKey) -> str | None: ...
    def action_id(self, key: HandlerKey) -> str | None: ...
    def actions_id(self, key: ModuleHandlerKey) -> str | None: ...
    def plugin_available(self, app: str, plugin: str) -> bool: ...
